### ISSUE TITLE
The mod can't load the music files

### ISSUE THREAD

**Issue by dgarroDC** [TitchMW/outerwildsmusicplayer#1]
I'm getting this error:

    DirectoryNotFoundException: Could not find a part of the path 'C:\Users\sherw\AppData\Roaming\OuterWildsModManager\OWML\Mods\Titch.OWMusicPlayer\MusicFiles'.Stacktrace: System.IO.__Error.WinIOError (System.Int32 errorCode, System.String maybeFullPath) (at <eae584ce26bc40229c1b1aa476bfa589>:0)System.IO.FileSystemEnumerableIterator`1[TSource].HandleError (System.Int32 hr, System.String path) (at <eae584ce26bc40229c1b1aa476bfa589>:0)System.IO.FileSystemEnumerableIterator`1[TSource].CommonInit () (at <eae584ce26bc40229c1b1aa476bfa589>:0)System.IO.FileSystemEnumerableIterator`1[TSource]..ctor (System.String path, System.String originalUserPath, System.String searchPattern, System.IO.SearchOption searchOption, System.IO.SearchResultHandler`1[TSource] resultHandler, System.Boolean checkHost) (at <eae584ce26bc40229c1b1aa476bfa589>:0)System.IO.FileSystemEnumerableFactory.CreateFileNameIterator (System.String path, System.String originalUserPath, System.String searchPattern, System.Boolean includeFiles, System.Boolean includeDirs, System.IO.SearchOption searchOption, System.Boolean checkHost) (at <eae584ce26bc40229c1b1aa476bfa589>:0)System.IO.Directory.InternalGetFileDirectoryNames (System.String path, System.String userPathOriginal, System.String searchPattern, System.Boolean includeFiles, System.Boolean includeDirs, System.IO.SearchOption searchOption, System.Boolean checkHost) (at <eae584ce26bc40229c1b1aa476bfa589>:0)System.IO.Directory.InternalGetFiles (System.String path, System.String searchPattern, System.IO.SearchOption searchOption) (at <eae584ce26bc40229c1b1aa476bfa589>:0)System.IO.Directory.GetFiles (System.String path, System.String searchPattern) (at <eae584ce26bc40229c1b1aa476bfa589>:0)System.IO.DirectoryInfo.GetFiles (System.String searchPattern) (at <eae584ce26bc40229c1b1aa476bfa589>:0)System.IO.DirectoryInfo.GetFilesSubdirs (System.Collections.ArrayList l, System.String pattern) (at <eae584ce26bc40229c1b1aa476bfa589>:0)System.IO.DirectoryInfo.GetFiles (System.String searchPattern, System.IO.SearchOption searchOption) (at <eae584ce26bc40229c1b1aa476bfa589>:0)(wrapper remoting-invoke-with-check) System.IO.DirectoryInfo.GetFiles(string,System.IO.SearchOption)MusicPlayer.MusicPlayer+<LoadAllAudio>d__17.MoveNext () (at <efd233c9b62f4826a93608bb72fb882d>:0)UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <469e86e97fa2467ebffe49bbd6086325>:0)UnityEngine.MonoBehaviour:StartCoroutine(String)MusicPlayer.MusicPlayer:<Start>b__13_0(OWScene, OWScene)LoadManager:OnSceneLoaded(Scene, LoadSceneMode)UnityEngine.SceneManagement.SceneManager:Internal_SceneLoaded(Scene, LoadSceneMode)

It seems the problem is that it tries to find the music files in `'C:\Users\sherw\AppData\Roaming\OuterWildsModManager\OWML\Mods\Titch.OWMusicPlayer\MusicFiles` which I guess is a path in your computer.  You could use `ModHelper.Manifest.ModFolderPath` to get the actual mod path, the music directory would be `ModHelper.Manifest.ModFolderPath + "MusicFiles"`.

Also, the repository doesn't have the code of your mod, it has the code of the template mod, could you update it please?

**Comment by MegaPiggy** [comment]
I made a fix for this.

[FixedDLL.zip](https://github.com/TitchMW/outerwildsmusicplayer/files/8356502/FixedDLL.zip)

In the code, I replaced `"C:\\Users\\sherw\\AppData\\Roaming\\OuterWildsModManager\\OWML\\Mods\\Titch.OWMusicPlayer\\MusicFiles"`
with
`Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData), "OuterWildsModManager\\OWML\\Mods\\Titch.OWMusicPlayer\\MusicFiles")`
